### ISSUE TITLE
Replay attack vulnerability 

### ISSUE THREAD

**Issue by ghost** [AlphaMailTeam/AlphaMailClient#1]
The alpha-mail protocol is vulnerable to a replay attack, an authentication message can literally be intercepted, then resent to the server from a malicious entity.

**Comment by JacobMisirian** [comment]
The most recent commit has fixed this error. Now each time a login occurs the server sends a random string of bytes to the user, who must combine the random bytes with their password hash and send the result back. The server checks them and authenticates if they match the server's result.
